### ISSUE TITLE
It should be able to generate from a JSON OpenAPI spec file

### ISSUE THREAD

**Issue by JaredCE** [tmizuma/openapi-test-data-generator#5]
**Is your feature request related to a problem? Please describe.**
Currently this only supports YAML OpenAPI spec files, but I think more and more, people are generating JSON spec files.

**Describe the solution you'd like**
JSON OpenAPI spec files should be accepted as an input

**Comment by tmizuma** [comment]
Thank you for submitting the feature request. 
JSON file format is now supported in version v3.1.0.

https://github.com/tmizuma/openapi-test-data-generator/releases/tag/v3.1.0
